import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import Modal from "../components/Modal";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";

export default function Home({trendingResults, providers, followResults}: any) {
  const {data: session} = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  if(!session) return <Login providers={providers}/>
  
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black flex min-h-screen max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed  />
        {isOpen && <Modal/>}
      </main>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}